Rocket details view
UVicRocketry/Ground-Support pull request #29
Opened 2023-06-22 01:11 UTC by j7uu

2023-06-22 01:13 UTC, j7uu commented
It's not done yet, but there was too much of it just sitting on my local

2023-06-24 21:02 UTC, klemie requested changes
W

2023-06-24 21:02 UTC, klemie commented on client/src/views/rocket-details-view.tsx
> +                                <Tab label="Item Three" />
```suggestion
                                <Tab label="Details" />
                                <Tab label="Components"  />
                                <Tab label="Missions" />

```

2023-06-24 21:02 UTC, klemie commented on client/src/views/rocket-details-view.tsx
> +                            <Tabs value={value} onChange={handleChange} aria-label="basic tabs example">
```suggestion
                            <Tabs value={value} onChange={handleChange}>

```

2023-06-24 21:02 UTC, klemie commented on client/src/views/rocket-details-view.tsx
> +                        </TabPanel>
```suggestion
                        <TabPanel value={value} index={0}>
                             Details
                        </TabPanel>
                        <TabPanel value={value} index={1}>
                            Components
                        </TabPanel>
                        <TabPanel value={value} index={2}>
                            Missions
                        </TabPanel>

```

2023-06-24 21:16 UTC, j7uu commented on client/src/views/rocket-details-view.tsx
> +    }
twas necessary

2023-06-24 21:16 UTC, j7uu commented on client/src/utils/view-provider.tsx
> +			{currentViewKey === (ROCKET_DETAILS_KEY) && currentView(ROCKET_DETAILS_KEY)}
W

2023-06-24 21:18 UTC, klemie approved these changes

2023-06-24 21:18 UTC, merged