Telemetry Packet Extraction
UVicRocketry/Ground-Support pull request #80
Opened 2024-06-18 06:31 UTC by JackCotter

Telemetry now extracts all info from packets including:
1. Callsign
2. Altitude
3. Latitude
4. Longitude

2024-06-18 06:34 UTC, JackCotter commented
This code currently has a bug where the rust server will send 2 packets back to back very quickly. This is because the front end is making 2 connections. This should be fixed in the Rocket Monitoring Refactor PR (#76).

2024-06-19 04:56 UTC, klemie requested changes

2024-06-19 04:56 UTC, klemie commented on services/telemetry/src/telemetry.rs
> +                    if let Some(pos) = buffer.windows(2).position(|window| window == b"\n\n") {
when I run the code it couldn't find two consecutive new lines. We should test this with the brb on Thursday 

I did this before the if statement and it worked fine with the mock data
```rs
 extract_packets(Arc::clone(&state_ref), buffer.clone()).await;
 buffer.clear();
```

2024-06-21 04:16 UTC, klemie commented
@PokeyOne Can you test this in your environment. WSL couldn't pick up `\n` in the packets for some reason, wondering if mac can. Might need to find a better bay detect locked packets.

2024-06-21 04:17 UTC, klemie commented on services/telemetry/src/telemetry.rs
> +                    if let Some(pos) = buffer.windows(2).position(|window| window == b"\n\n") {
@JackCotter Could we add a `Locked` attribute to the packet so we can more easily tell on the frontend if we've got a lock or not

2024-09-27 18:14 UTC, merged